version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME:-app}_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-app_dev}
      POSTGRES_USER: ${DB_USER:-dev_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-dev_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME:-app}_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-dev_redis_pass}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Local S3 (MinIO)
  minio:
    image: minio/minio:latest
    container_name: ${PROJECT_NAME:-app}_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-minioadmin123}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Local SMTP Server (for email testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT_NAME:-app}_mailhog
    ports:
      - "${MAIL_SMTP_PORT:-1025}:1025"  # SMTP
      - "${MAIL_WEB_PORT:-8025}:8025"   # Web UI
    logging:
      driver: "none"  # Disable logging

  # Local Mock API Server
  mockserver:
    image: mockserver/mockserver:latest
    container_name: ${PROJECT_NAME:-app}_mockserver
    environment:
      MOCKSERVER_LOG_LEVEL: INFO
    ports:
      - "${MOCK_API_PORT:-1080}:1080"
    volumes:
      - ./mocks:/config
    command: -serverPort 1080 -configurationFile /config/mockserver.json

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  default:
    name: ${PROJECT_NAME:-app}_network